#!/usr/bin/env Rscript

# Generate the GRF landscapes used for the CIN study. Parameterization follows
# the ALFA-K source accompanying s41467-025-67750-0:
# 22 chromosome dimensions, 10 centroids, centroid coordinates in -10:20,
# centroid coordinates in -10:20, and wavelength range 0.2--1.6.

args <- commandArgs(trailingOnly = TRUE)
project_dir <- if (length(args)) normalizePath(args[[1]]) else getwd()
out_dir <- file.path(project_dir, "data", "landscapes")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

set.seed(20260712)
n_landscapes <- 200L
n_chromosomes <- 22L
n_centroids <- 10L
lambda_min <- 0.2
lambda_max <- 1.6

# One-dimensional Latin hypercube: exactly one lambda from each stratum.
lambda <- ((seq_len(n_landscapes) - stats::runif(n_landscapes)) / n_landscapes)
lambda <- sample(lambda_min + lambda * (lambda_max - lambda_min))

manifest <- vector("list", n_landscapes)
for (i in seq_len(n_landscapes)) {
  landscape_seed <- 20260712L + i
  set.seed(landscape_seed)
  centroids <- matrix(
    sample(-10:20, n_centroids * n_chromosomes, replace = TRUE),
    nrow = n_centroids,
    ncol = n_chromosomes
  )
  landscape_id <- sprintf("landscape_%02d", i)
  landscape <- list(
    landscape_id = landscape_id,
    centroids = centroids,
    lambda = lambda[[i]],
    n_centroids = n_centroids,
    n_chromosomes = n_chromosomes,
    centroid_coordinate_range = c(-10L, 20L),
    generation_seed = landscape_seed,
    source = "ALFA-K supplementary source: scripts/S01_run_abm_sims.R and R/utils_karyo.R"
  )
  landscape_path <- file.path(out_dir, paste0(landscape_id, ".rds"))
  saveRDS(landscape, landscape_path)
  utils::write.csv(
    data.frame(centroid_id = seq_len(n_centroids), centroids, check.names = FALSE),
    file.path(out_dir, paste0(landscape_id, "_centroids.csv")),
    row.names = FALSE
  )
  manifest[[i]] <- data.frame(
    landscape_id = landscape_id,
    lambda = lambda[[i]],
    n_centroids = n_centroids,
    n_chromosomes = n_chromosomes,
    centroid_min = min(centroids),
    centroid_max = max(centroids),
    generation_seed = landscape_seed,
    stringsAsFactors = FALSE
  )
}

manifest <- do.call(rbind, manifest)
utils::write.csv(manifest, file.path(out_dir, "manifest.csv"), row.names = FALSE)
saveRDS(manifest, file.path(out_dir, "manifest.rds"))
writeLines(c(
  "# Synthetic GRF landscapes",
  "",
  "Two hundred landscapes generated by Latin-hypercube sampling of lambda on [0.2, 1.6].",
  "All other GRF settings are fixed to the authors' synthetic-validation design:",
  "22 chromosome dimensions, 10 centroids, and centroids sampled from integers -10 through 20.",
  "Each RDS contains the complete reproducible landscape definition."
), file.path(out_dir, "README.md"))
